version: '3.9'

services:
  app:
    build:
      context: ./docker/build/app
      dockerfile: Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: hub-app
    depends_on:
      - mailpit
      - mariadb
      - meilisearch
      - minio
      - redis
    restart: always
    userns_mode: keep-id
    user: ${UID:-1000}:${GID:-1000}
    ports:
      - '${VITE_APP_PORT:-5173}:${VITE_APP_PORT:-5173}'
    volumes:
      - .:/app:rw,z,U
    secrets:
      - source: ssl-cert
        target: cert.pem
      - source: ssl-key
        target: key.pem
      - source: ssl-dhparam
        target: dhparam.pem
    networks:
      - hub
  nginx:
    build:
      context: ./docker/build/nginx
      dockerfile: Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: hub-nginx
    depends_on:
      - app
    restart: always
    userns_mode: keep-id
    user: ${UID:-1000}:${GID:-1000}
    hostname: hub.test
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${HTTP_PORT:-80}:8080'
      - '${HTTPS_PORT:-443}:4443'
    volumes:
      - .:/app:ro,z
    secrets:
      - source: ssl-cert
        target: cert.pem
      - source: ssl-key
        target: key.pem
      - source: ssl-dhparam
        target: dhparam.pem
    networks:
      - hub
  mariadb:
    image: mariadb:latest
    container_name: hub-mariadb
    environment:
      MARIADB_AUTO_UPGRADE: ${MARIADB_AUTO_UPGRADE:-true}
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    restart: always
    ports:
      - '${DB_PORT:-3306}:3306'
    volumes:
      - mariadb:/var/lib/mysql:rw,Z
    networks:
      - hub
  redis:
    image: redis:latest
    container_name: hub-redis
    restart: always
    expose:
      - '${REDIS_PORT:-6379}'
    volumes:
      - redis:/data:rw,Z
    networks:
      - hub
  minio:
    image: minio/minio:latest
    command: minio server /data/minio --console-address ":8900"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-hub}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_USER:-password}
    ports:
      - '${MINIO_PORT:-9000}:9000'
      - '${MINIO_CONSOLE_PORT:-8900}:8900'
    volumes:
      - minio:/data/minio
    networks:
      - hub
  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: hub-meilisearch
    environment:
      MEILI_MASTER_KEY: '${MEILISEARCH_KEY}'
      MEILI_NO_ANALYTICS: ${MEILISEARCH_ANALYTICS:-true}
      MEILI_ENV: '${MEILISEARCH_ENV:-development}'
    restart: always
    ports:
      - '${MEILISEARCH_PORT:-7700}:7700'
    volumes:
      - meilisearch:/meili_data:rw,Z
    networks:
      - hub
  mailpit:
    image: axllent/mailpit:latest
    container_name: hub-mailpit
    restart: always
    ports:
      - '${MAILPIT_PORT:-1025}:1025'
      - '${MAILPIT_DASHBOARD_PORT:-8025}:8025'
    networks:
      - hub
secrets:
  ssl-cert:
    file: ./docker/ssl/cert.pem
  ssl-key:
    file: ./docker/ssl/key.pem
  ssl-dhparam:
    file: ./docker/ssl/dhparam.pem
volumes:
  mariadb:
    name: hub-mariadb
  redis:
    name: hub-redis
  minio:
    name: hub-minio
  meilisearch:
    name: hub-melisearch
networks:
  hub:
    driver: bridge
