global:
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: true

serversTransport:
  insecureSkipVerify: true

providers:
  docker:
    network: podman
    exposedByDefault: false
  file:
    filename: /etc/traefik/dynamic.yml

log:
  level: INFO
  format: common

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
