global:
  sendAnonymousUsage: false

log:
  level: INFO
  format: common

api:
  dashboard: true

providers:
  docker:
    watch: true
    network: traefik
    exposedByDefault: false
  file:
    filename: /etc/traefik/dynamic.yml

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    http3: {}
