global:
  sendAnonymousUsage: false

api:
  dashboard: true

providers:
  docker:
    network: traefik
    exposedByDefault: false
  file:
    filename: /etc/traefik/dynamic.yml

log:
  level: INFO
  format: common

entryPoints:
  name:
    http3: {}
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443/udp"
